services:
  rabbitMQ:
    container_name: rabbitmq-service-${env}
    image: 'rabbitmq:management-alpine'
    restart: always
    volumes:
      - ../rabbitMQ/advanced.config:/etc/rabbitmq/advanced.config
      - ../rabbitMQ/rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ../rabbitMQ/rabbitmq-test.conf:/etc/rabbitmq/rabbitmq.conf
      - ../rabbitMQ/logs:/var/log/rabbitmq
    ports:
      - '0.0.0.0:${rmqPort}:5672'
      - '0.0.0.0:${rmqHttpPort}:15672'
    networks:
      - real-time-to-do-network
    environment:
      - RABBITMQ_DEFAULT_USER=${rmqUser}
      - RABBITMQ_DEFAULT_PASS=${rmqPassword}
    logging:
      driver: 'json-file'
      options:
        max-size: '128m'
        max-file: 25

networks:
  real-time-to-do-network:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.16.254.0/24
    #       gateway: 172.16.254.1
